name: learn-github-actions-dev
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: main
    # tags:
    #   - 'v*'

env:
  STAGE_STAGING: Staging

jobs:
  deploy:
    uses: qrusadorz/learn-github-actions/.github/workflows/deploy.yml@main
    with:
      envstagevalue: Staging
  