name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: main
 
env:
  # DAY_OF_WEEK: ${{ github.actor }}
  LLF: ${{ vars.LGA_FILE_NAME }}
    
jobs:
  build:
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     stage: ['stg', 'prod']
    strategy:
      matrix:
        environment: [Staging, Production]
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: echo ${{ matrix.stage }}
      - run: npm install -g bats
      - run: bats -v > output.log
      - name: Upload ouput file
        uses: actions/upload-artifact@v3
        with:
          name: ouput-log-file
          path: output.log
      - run: echo ${{ env.LLF }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  deploy:
    # if: ${{ github.ref == 'refs/heads/main' }}
    # needs: [build]
    # environment: Production
    # environment: Staging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Staging, Production]
    environment: ${{ matrix.environment }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo ${{ env.LLF }}

   